{"name": "测试数据：【 测试test，123456，False，1003，用户名不存在】", "status": "broken", "statusDetails": {"message": "KeyError: 'msg'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x050BCD30>\nusername = '测试test', password = '123456', except_result = False\nexcept_code = 1003, except_msg = '用户名不存在'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n>       result = login_user(username, password)\n\ntest_03_login.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nusername = '测试test', password = '123456'\n\n    def login_user(username, password):\n        \"\"\"\n        登录用户\n        :param username: 用户名\n        :param password: 密码\n        :return: 自定义的关键字返回结果 result\n        \"\"\"\n        result = ResultBase()\n        payload = {\n            \"username\": username,\n            \"password\": password\n        }\n        header = {\n            \"Content-Type\": \"application/json\"\n        }\n        res = user.login(data=json.dumps(payload), headers=header)\n        print(res.json())\n        result.success = False\n        if res.json()[\"code\"] == 200:\n            result.success = True\n            result.token = res.json()[\"login_info\"][\"data\"]\n            print(result.token)\n        else:\n>           result.error = \"接口返回码是 【 {} 】, 返回信息：{} \".format(res.json()[\"code\"], res.json()[\"msg\"])\nE           KeyError: 'msg'\n\nuser.py:99: KeyError"}, "description": "该用例是针对获取用户登录接口的测试", "attachments": [{"name": "log", "source": "90a903d0-a478-4a8c-a777-d1008eae8b8d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3aa597e6-bbf0-4156-b631-7d805d3b18d4-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e60f0e3d-acea-4d1e-9d62-16a18cb3a3f7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1003"}, {"name": "except_msg", "value": "'用户名不存在'"}], "start": 1622540420420, "stop": 1622540420446, "uuid": "7e6ed568-b4ce-4471-b87c-2748b192d262", "historyId": "56bfc4b39b0fa959e074da77d0878485", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "12464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://www.cnblogs.com/wintest", "name": "点击，跳转到对应BUG的链接地址"}]}