{"name": "测试数据：【 admin，123456，True，200，success】", "status": "broken", "statusDetails": {"message": "AttributeError: 'ResultBase' object has no attribute 'msg'", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04861A70>\nusername = 'admin', password = '123456', except_result = True, except_code = 200\nexcept_msg = 'success'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n        assert result.response.json().get(\"code\") == except_code\n>       assert except_msg in result.msg\nE       AttributeError: 'ResultBase' object has no attribute 'msg'\n\ntest_03_login.py:35: AttributeError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1622552222087, "stop": 1622552222087}], "attachments": [{"name": "log", "source": "f203af09-98fe-4bb8-9de4-083d731949fe-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "72f773c3-ebac-4421-972a-cca02e38694c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "fd741266-a007-4d11-8613-d69db5a45b96-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "200"}, {"name": "except_msg", "value": "'success'"}], "start": 1622552222044, "stop": 1622552222088, "uuid": "8a2aaa6b-0118-4042-b83b-4692f1ecaed8", "historyId": "1ff237c079aafda41463d2ce0dab12c6", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "5548-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}