{"name": "测试数据：【 admin，123456，True，0，登录成功】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 0", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04FAFF50>\nusername = 'admin', password = '123456', except_result = True, except_code = 0\nexcept_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n>       assert result.response.json().get(\"code\") == except_code\nE       assert 200 == 0\n\ntest_03_login.py:34: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1622549334459, "stop": 1622549334460}], "attachments": [{"name": "log", "source": "c0d158d5-1ba6-4b10-9e77-a30dd49af78a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "116bd466-e8b2-4bfe-8f59-ebdbed5be647-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cbcca092-7ab2-4760-8196-b083e9ca7da1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "0"}, {"name": "except_msg", "value": "'登录成功'"}], "start": 1622549334413, "stop": 1622549334461, "uuid": "03f73043-f1eb-4cef-9329-4b9acb6ce777", "historyId": "d501403046e9bb0114eef52aa0e49e6f", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "story", "value": "用例--登录用户"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "16032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}