{"name": "测试数据：【 测试test，False，100022，账号不存在，请重新输入或联系管理员！】", "status": "passed", "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622569885600, "stop": 1622569885601}], "attachments": [{"name": "log", "source": "146de367-e909-4ecd-9286-1a7bb4d43480-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "841f20de-c699-4115-be53-13ff1d1dfbf1-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e55617ff-7d61-4a39-8509-abbde3066331-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "100022"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622569885581, "stop": 1622569885603, "uuid": "a200818a-211d-46e2-aa3a-5ac1a0e23d4c", "historyId": "48cf703ec6a16990ff54539c4bc7ebf1", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "epic", "value": "针对单个接口的测试"}, {"name": "feature", "value": "用户登录模块"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "21668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}