{"name": "测试数据：【 测试test，123456，False，1003，用户名不存在】", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100017 == 1003\n +  where 100017 = <built-in method get of dict object at 0x04B81C90>('code')\n +    where <built-in method get of dict object at 0x04B81C90> = {'code': 100017, 'data': 'failed', 'message': '该用户不存在'}.get\n +      where {'code': 100017, 'data': 'failed', 'message': '该用户不存在'} = <bound method Response.json of <Response [200]>>()\n +        where <bound method Response.json of <Response [200]>> = <Response [200]>.json\n +          where <Response [200]> = <core.result_base.ResultBase object at 0x04B8E770>.response", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x04BD8710>, username = '测试test', password = '123456', except_result = False, except_code = 1003, except_msg = '用户名不存在'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    @allure.issue(\"http://10.5.15.116/#/home\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"暂无\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n>       assert result.response.json().get(\"code\") == except_code\nE       AssertionError: assert 100017 == 1003\nE        +  where 100017 = <built-in method get of dict object at 0x04B81C90>('code')\nE        +    where <built-in method get of dict object at 0x04B81C90> = {'code': 100017, 'data': 'failed', 'message': '该用户不存在'}.get\nE        +      where {'code': 100017, 'data': 'failed', 'message': '该用户不存在'} = <bound method Response.json of <Response [200]>>()\nE        +        where <bound method Response.json of <Response [200]>> = <Response [200]>.json\nE        +          where <Response [200]> = <core.result_base.ResultBase object at 0x04B8E770>.response\n\ntestcases\\api_test\\test_03_login.py:34: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622550392370, "stop": 1622550392370}], "attachments": [{"name": "log", "source": "77d885fb-da8a-4667-be7e-99a5388b91a5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a2c3b119-c93e-4a89-b784-18c067f69536-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "1003"}, {"name": "except_msg", "value": "'用户名不存在'"}], "start": 1622550392349, "stop": 1622550392372, "uuid": "cee17274-6215-48d7-a47a-8744048dd2c1", "historyId": "56bfc4b39b0fa959e074da77d0878485", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "5600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}