{"name": "测试数据：【 测试test，False，100022，账号不存在，请重新输入或联系管理员！】", "status": "passed", "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1622569998842, "stop": 1622569998842}], "attachments": [{"name": "log", "source": "69407ddb-1185-4ff2-aef5-f910599471dc-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1b03febd-5a67-4e80-b65a-d4ced0d84592-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "23675f69-a66a-4df2-9b08-f52bfaa66017-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "100022"}, {"name": "except_msg", "value": "'账号不存在，请重新输入或联系管理员！'"}], "start": 1622569998823, "stop": 1622569998843, "uuid": "1e04036b-caf8-4e22-a41a-bf867d6ff598", "historyId": "48cf703ec6a16990ff54539c4bc7ebf1", "testCaseId": "4965f76335de5c80d0580a0c1fbc27f9", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_check_user", "labels": [{"name": "feature", "value": "用户登录模块"}, {"name": "story", "value": "用例--检查登录用户"}, {"name": "severity", "value": "normal"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-1UC29CD2"}, {"name": "thread", "value": "18320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}], "links": [{"type": "test_case", "url": "暂无", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "http://10.5.15.116/#/home", "name": "点击，跳转到对应BUG的链接地址"}]}